name: jubilee-openoil-g2
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - numpy
  - pandas
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - h5netcdf
  - pip
  - pip:
      - opendrift==1.14.12
